### ISSUE TITLE
Password insecure

### ISSUE THREAD

**Issue by RayHughes** [ramantehlan/AlvisAI#2]
Currently the password is being stored in a session and being hashed via MD5. MD5 is an insecure hashing algorithm that is easily crackable. It is recommend that you use ARGON or BCRYPT. 

Additionally you should never store a password in a session. If your sessions are exploded by a co-existing application on the server, so are your passwords.

https://github.com/ramantehlan/AlvisAI/blob/77025dafd042af1d8987c6d0a40b7b55b4605e4d/signup/upload_information.php#L302

**Comment by ramantehlan** [comment]
Right, the current implementation is very insecure, the password should never be stored in a session and the hashing algorithm should also be different. Though this source code is not in production and it's here just as an archive, which is why I won't be solving this issue.

But, thank you for pointing this issue out. :)

**Comment by RayHughes** [comment]
Why would you close the issue if you open sourced it? Someone else could pick it up and address it. It is the whole point of open sourcing something.

**Comment by ramantehlan** [comment]
I understand what open source is about, but this project is just an archive. It's not in production anywhere, which is why I closed the issue. 

Though, if you feel you want to pick it and address it, I can reopen it.

**Comment by ramantehlan** [comment]
@RayHughes I intended to keep it open source and accept contributions, but it's a very old code and not it use, so there were no contributions, so I treated it as an archive, but I agree, later I shouldn't have kept it open source without archiving it, I apologize for the same and will an archive it, ASAP. 

Thank you for your contribution. :)
